// Procedural animation primitives — motion generated by math, not baked clips.
// Dependency-free (uses vecmath). Drive bones/transforms each frame with a delta time.
//
// Bridge to Three.js: read a THREE.Vector3 with v.toArray(), write back with v.fromArray(result);
// for quaternions use q.toArray() / q.fromArray().

import { clamp, sub, add, scale, len, norm, dot, cross, quatAngle } from './vecmath.js';

/**
 * Critically-damped spring for a scalar (or use SpringVec3). Frame-rate independent, no overshoot
 * by default. Great for camera follow, UI, aim, recoil, "juice".
 *   const s = new Spring(); s.target = 10; each frame: value = s.update(dt);
 */
export class Spring {
  constructor({ stiffness = 120, damping = 20, value = 0 } = {}) {
    this.k = stiffness; this.c = damping; this.value = value; this.vel = 0; this.target = value;
  }
  update(dt) {
    // semi-implicit Euler; clamp dt for stability after stalls
    const h = Math.min(dt, 1 / 30);
    const force = -this.k * (this.value - this.target) - this.c * this.vel;
    this.vel += force * h;
    this.value += this.vel * h;
    return this.value;
  }
}

/** Vec3 spring — three independent springs sharing gains. */
export class SpringVec3 {
  constructor(opts = {}) {
    this.x = new Spring(opts); this.y = new Spring(opts); this.z = new Spring(opts);
  }
  setTarget([x, y, z]) { this.x.target = x; this.y.target = y; this.z.target = z; }
  update(dt) { return [this.x.update(dt), this.y.update(dt), this.z.update(dt)]; }
}

/**
 * Frame-rate-independent exponential smoothing (a.k.a. "damp"). Moves `current` toward `target`
 * by a fraction that depends only on `lambda` and elapsed time — the correct way to lerp per frame.
 * Higher lambda = snappier. Returns the new scalar.
 */
export function damp(current, target, lambda, dt) {
  return target + (current - target) * Math.exp(-lambda * dt);
}
export function dampVec3(current, target, lambda, dt) {
  const t = 1 - Math.exp(-lambda * dt);
  return [
    current[0] + (target[0] - current[0]) * t,
    current[1] + (target[1] - current[1]) * t,
    current[2] + (target[2] - current[2]) * t,
  ];
}

/**
 * Two-bone (analytic) IK — the workhorse for arms and legs. Given the root joint position, a
 * target, the two bone lengths, and a pole direction (which way the elbow/knee bends), returns the
 * world positions of the three joints. If the target is out of reach, the limb points at it fully
 * extended (reachable=false). Feed the returned positions to bone look-rotations to pose the limb.
 *
 *   const { root, mid, end, reachable } = twoBoneIK(shoulderPos, handTarget, upperLen, foreLen, poleDir);
 */
export function twoBoneIK(root, target, lenA, lenB, poleDir = [0, 0, 1]) {
  const toTarget = sub(target, root);
  let d = len(toTarget);
  const maxD = lenA + lenB;
  const minD = Math.abs(lenA - lenB);
  const reachable = d <= maxD + 1e-6 && d >= minD - 1e-6;
  d = clamp(d, minD + 1e-6, maxD - 1e-6);
  const dir = len(toTarget) > 1e-9 ? norm(toTarget) : [0, 1, 0];

  // Angle at the root between (root→target) and (root→mid), by law of cosines.
  const cosRoot = clamp((lenA * lenA + d * d - lenB * lenB) / (2 * lenA * d), -1, 1);
  const a = Math.acos(cosRoot);

  // Bend plane: component of the pole hint perpendicular to `dir`.
  let bend = sub(poleDir, scale(dir, dot(poleDir, dir)));
  if (len(bend) < 1e-6) {
    bend = sub([0, 1, 0], scale(dir, dot([0, 1, 0], dir)));
    if (len(bend) < 1e-6) bend = [1, 0, 0];
  }
  bend = norm(bend);

  const midDir = add(scale(dir, Math.cos(a)), scale(bend, Math.sin(a)));
  const mid = add(root, scale(midDir, lenA));
  const end = add(root, scale(dir, d)); // effector lands here (clamped to reach)
  return { root, mid, end, reachable };
}

/**
 * Look-at with a rate limit (radians/sec) so aiming/turning eases in instead of snapping.
 * Returns the new forward vector. Combine with quatLookRotation to build the bone/object quaternion.
 */
export function turnToward(currentForward, desiredForward, maxRadPerSec, dt) {
  const cf = norm(currentForward), df = norm(desiredForward);
  const total = Math.acos(clamp(dot(cf, df), -1, 1));
  if (total < 1e-6) return df;
  const step = Math.min(1, (maxRadPerSec * dt) / total);
  return norm([
    cf[0] + (df[0] - cf[0]) * step,
    cf[1] + (df[1] - cf[1]) * step,
    cf[2] + (df[2] - cf[2]) * step,
  ]);
}

/** Layered value noise for organic idle/breathing/sway (deterministic, seedable). */
export function idleNoise(t, { freq = 1, amp = 1, octaves = 2, seed = 0 } = {}) {
  let v = 0, a = amp, f = freq;
  for (let o = 0; o < octaves; o++) {
    v += a * Math.sin((t * f + seed * 1.37 + o * 2.1) * 6.2831853) * 0.5;
    a *= 0.5; f *= 2;
  }
  return v;
}

export { quatAngle };
