// sonde ch06 (Bible 06, les 8) — 1, 3, 8, 9, 10, 11-13, 14, 16, 18, 19, 20, 24, 25, 27, 28 sur 2 × 90 min (4-3-3 : les 8 = postes 4 et 6).
import { makeMatch, matchStep, matchCfg } from '../../assets/starter/src/engine/match-sim.js';
import { momentDuJeu } from '../../assets/starter/src/engine/phases.js';
const seeds = (process.argv[2] ?? '3,7').split(',').map(Number);
const o = { n: 0, dist8: 0, dist8IP: 0, dist8OP: 0, imgsProg: 0, deuxDemi: 0, couloirOk: 0, bandeOk: 0, imgsOff: 0, rd: { def: [], sup: [], larg: [], long: [], dBut: [] }, boxAtCross: [], deux88: 0, nPoss8: 0, hold8: [], soutien: { BU1: [], BU2: [], CRE: [], FIN: [] }, cp: { delai: [], dArr: [] }, contres: [], double: 0, imgsMid: 0, jeu: 0 };
for (const seed of seeds) {
  const st = makeMatch({ full: true, seed }), cfg = matchCfg({ shotRange: 20, chrono: { periodes: 2, duree: 2700, pause: 10 } }); o.n++;
  const huit = [0, 1].map((t) => st.players.filter((p) => p.team === t && (p.post === 4 || p.post === 6)));
  let seen = 0, carrierPrev = -1, holdT0 = 0, prevPoss = -1, lossAt = -1, lossTeam = -1, cpDone = false, contreT0 = -1; const prevP = new Map(); const hz = st.pitch.hz, hx = st.pitch.hx, W = hz * 2 / 5;
  const couloir = (z) => Math.min(4, Math.max(0, Math.floor((z + hz) / W)));
  for (let i = 0; i < 5400 * 60; i++) {
    matchStep(st, 1 / 60, cfg); if (st.restart?.type === 'fin') break; if (!st.restart) o.jeu++;
    for (const t of [0, 1]) for (const p of huit[t]) { const pv = prevP.get(p.id); if (pv) { const d = Math.hypot(p.p[0] - pv[0], p.p[2] - pv[1]); o.dist8 += d; if (st.possession.team === t) o.dist8IP += d; else if (st.possession.team === 1 - t) o.dist8OP += d; } prevP.set(p.id, [p.p[0], p.p[2]]); }
    const ow = st.ball.owner ?? -1; if (ow !== carrierPrev) { if (carrierPrev >= 0 && huit.flat().some((p) => p.id === carrierPrev)) { o.hold8.push(st.t - holdT0); o.nPoss8++; } carrierPrev = ow; holdT0 = st.t; }
    const poss = st.possession.team;
    if (poss !== prevPoss) { if (prevPoss >= 0 && poss >= 0 && !st.restart) { lossAt = st.t; lossTeam = prevPoss; cpDone = false; const og = st.pitch.ownGoal(prevPoss), sg = Math.sign(og.x || 1); if (Math.abs(st.ball.p[0] - og.x) > 55 && momentDuJeu(st, prevPoss, 6) !== 'transition-off') { const zoneDef = st.players.filter((p) => p.team === prevPoss && !p.keeper && (p.p[0] - st.ball.p[0]) * sg > 0); const zoneAtt = st.players.filter((p) => p.team === poss && !p.keeper && (p.p[0] - st.ball.p[0]) * sg > 0); o.rd.def.push(zoneDef.length); o.rd.sup.push(zoneDef.length - zoneAtt.length); if (zoneDef.length >= 2) { const zs = zoneDef.map((p) => p.p[2]), xs = zoneDef.map((p) => Math.abs(p.p[0] - og.x)); o.rd.larg.push(Math.max(...zs) - Math.min(...zs)); o.rd.long.push(Math.max(...xs) - Math.min(...xs)); o.rd.dBut.push(xs.reduce((a, b) => a + b, 0) / xs.length); } } if (contreT0 < 0) contreT0 = st.t; } if (poss === lossTeam && contreT0 >= 0 && st.t - contreT0 < 30) { o.contres.push(st.t - contreT0); } contreT0 = poss >= 0 ? st.t : -1; prevPoss = poss; }
    if (!cpDone && lossAt >= 0 && st.t - lossAt < 6) { const c = st.possession.carrier >= 0 ? st.players[st.possession.carrier] : null; if (c && c.team !== lossTeam) { const near = huit[lossTeam].map((p) => Math.hypot(p.p[0] - c.p[0], p.p[2] - c.p[2])); const m = Math.min(...near); if (m < 1.5) { o.cp.delai.push(st.t - lossAt); o.cp.dArr.push(m); cpDone = true; } } }
    for (; seen < st.events.length; seen++) { const e = st.events[seen]; if (e.type === 'centre') { const by = st.players[e.by]; const g = st.pitch.attackGoal(by.team); o.boxAtCross.push(st.players.filter((p) => p.team === by.team && !p.keeper && Math.abs(p.p[0] - g.x) < 16.5 && Math.abs(p.p[2]) < 20.16).length); } }
    if (st.restart || i % 15 || poss < 0) continue;
    const og = st.pitch.ownGoal(poss), sg = Math.sign(og.x || 1), gA = st.pitch.attackGoal(poss); const xB = Math.abs(st.ball.p[0] - og.x);
    const att = st.players.filter((p) => p.team === poss && !p.keeper && p.down <= 0);
    if (momentDuJeu(st, poss, 6) === 'attaque-placée') { o.imgsOff++; const cnt = [0, 0, 0, 0, 0]; for (const p of att) cnt[couloir(p.p[2])]++; if (cnt.every((c) => c <= 2)) o.couloirOk++; const bands = {}; for (const p of att) { const b = Math.floor(Math.abs(p.p[0] - og.x) / 8); bands[b] = (bands[b] ?? 0) + 1; } if (Object.values(bands).every((c) => c <= 3)) o.bandeOk++; if (xB > 35 && xB < 80) { o.imgsProg++; if (cnt[1] >= 1 && cnt[3] >= 1) o.deuxDemi++; } }
    if (huit[poss].every((p) => Math.abs(p.p[0] - gA.x) < 17)) o.deux88++;
    const c = st.possession.carrier >= 0 ? st.players[st.possession.carrier] : null; if (c) { const sp = xB < 25 ? 'BU1' : xB < 52.5 ? 'BU2' : xB < 88.5 ? 'CRE' : 'FIN'; for (const p of huit[poss]) if (p.id !== c.id) o.soutien[sp].push(Math.hypot(p.p[0] - c.p[0], p.p[2] - c.p[2])); }
    const def = 1 - poss; if (momentDuJeu(st, def, 6) === 'défense-placée') { o.imgsMid++; const ogD = st.pitch.ownGoal(def), sgD = Math.sign(ogD.x || 1); const D = st.players.filter((p) => p.team === def && !p.keeper && p.post < 4); const ligneD = Math.min(...D.map((p) => Math.abs(p.p[0] - ogD.x))); const entre = st.players.filter((p) => p.team === poss && !p.keeper && p.id !== (c?.id ?? -1) && Math.abs(p.p[0] - ogD.x) > ligneD + 4 && Math.abs(p.p[0] - ogD.x) < ligneD + 22); let dbl = false; for (const a of entre) { const marqueurs = st.players.filter((q) => q.team === def && !q.keeper && q.job === 'mark' && q.target && Math.hypot(q.target[0] - a.p[0], q.target[2] - a.p[2]) < 3).length; if (marqueurs >= 2) dbl = true; } if (dbl) o.double++; }
  }
}
const q = (a, x) => { a = [...a].sort((u, v) => u - v); return a.length ? a[Math.floor(x * a.length)] : NaN; }; const mean = (a) => a.length ? a.reduce((x, y) => x + y, 0) / a.length : NaN;
console.log(`${o.n} × 90 min, ${(o.jeu / 3600 / o.n).toFixed(0)} min de jeu / match`);
console.log(`1   distance d'un 8 : ${(o.dist8 / 4 / o.n).toFixed(0)} m (10 500-11 500) ; 3 rapport hors possession / en possession ${(o.dist8OP / Math.max(1, o.dist8IP)).toFixed(2)} (cible 1,16)`);
console.log(`8   les deux demi-espaces occupés en progression : ${(100 * o.deuxDemi / Math.max(1, o.imgsProg)).toFixed(0)} % (≥ 80) ; 9 ≤ 2 par couloir ${(100 * o.couloirOk / Math.max(1, o.imgsOff)).toFixed(0)} % des images (≥ 95) ; 10 ≤ 3 par bande de 8 m ${(100 * o.bandeOk / Math.max(1, o.imgsOff)).toFixed(0)} % (≥ 95)`);
console.log(`11  rest defense à la perte : défenseurs derrière ${mean(o.rd.def).toFixed(1)} (3,7 ±0,8), supériorité ${mean(o.rd.sup).toFixed(1)} (+1,7) ; 12 largeur ${mean(o.rd.larg).toFixed(1)} m (28,2) / longueur ${mean(o.rd.long).toFixed(1)} m (7,4) ; 13 distance au but ${mean(o.rd.dBut).toFixed(1)} m (43,6) — sur ${o.rd.def.length} pertes`);
console.log(`14  attaquants dans la surface au centre : p50 ${q(o.boxAtCross, 0.5)}, p90 ${q(o.boxAtCross, 0.9)} (≤ 3-4 dans 90 %) ; 16 les deux 8 à moins de 17 m du but adverse : ${(o.deux88 / o.n / 4).toFixed(0)} s / match (≤ 3 occurrences)`);
console.log(`18  possessions du 8 / 10 min : ${(o.nPoss8 / 4 / (o.jeu / 3600) * 10).toFixed(1)} (16,5 ±8,6) ; 19 durée p50 ${q(o.hold8, 0.5).toFixed(2)} s, moyenne ${mean(o.hold8).toFixed(2)} (≈ 0,9)`);
console.log(`20  distance de soutien du 8 au porteur : BU1 ${q(o.soutien.BU1, 0.5).toFixed(1)} > BU2 ${q(o.soutien.BU2, 0.5).toFixed(1)} > CRE ${q(o.soutien.CRE, 0.5).toFixed(1)} > FIN ${q(o.soutien.FIN, 0.5).toFixed(1)} m (décroissance monotone, écart ≥ 3)`);
console.log(`24  délai perte → premier contact de contre-pressing d'un 8 (< 1,5 m) : p50 ${q(o.cp.delai, 0.5).toFixed(2)} s (1,0-2,5) sur ${o.cp.delai.length} ; 25 distance d'arrivée p50 ${q(o.cp.dArr, 0.5).toFixed(2)} m (0,3-0,8)`);
console.log(`27  durée des contre-attaques subies (possession adverse née d'une perte, < 30 s) : moyenne ${mean(o.contres).toFixed(1)} s (10,9 ±0,6) ; 28 double marquage entre les lignes : ${(100 * o.double / Math.max(1, o.imgsMid)).toFixed(1)} % des images de bloc (≤ 5)`);
