// sonde 281 — TROIS RETOURS UTILISATEUR (16/09, showcase-pi-mocha) : (1) « chaque coup franc, l'équipe qui tire vient à 10 autour du
// ballon » — les corps de l'équipe qui remet à ≤ 6 m du ballon juste avant la remise, par type de remise ; (2) « trop de mauvaises
// passes : dans le dos du receveur, demi-tours » — part des passes reçues dans le dos (ballon venant de derrière le regard du receveur
// au départ) et part des receveurs qui font un demi-tour (> 120° de lacet dans les 1,5 s) ; (3) « les conduites ne sont pas fluides,
// le ballon s'éloigne » — pendant le port (phase carry, porteur en mouvement) : distance ballon-porteur p50 / p90 / max par touche, et
// part des touches où le ballon part à plus de 2,5 m du pied.
import { makeMatch, matchStep, matchCfg } from '/home/user/three-js-aaa-agent-skill/skills/threejs-aaa/assets/starter/src/engine/match-sim.js';
const seeds = (process.argv[2] ?? '3,7').split(',').map(Number), over = JSON.parse(process.argv[3] ?? '{}'), DUR = +(process.argv[4] ?? 1200);
const hyp = Math.hypot, wrap = (a) => Math.atan2(Math.sin(a), Math.cos(a));
const o = { restarts: {}, passes: 0, dos: 0, demi: 0, retour: 0, dosRecu: 0, touches: [], loin: 0, dist: [], n: 0, pousse: [], pousseLoin: 0, recues: 0, v0: [], d05: [], perdu: 0, log: [], repris: [], tRepris: [], demiAvant: 0, demiApres: 0, demiAvantCourse: 0, demiAvantArret: 0, demiAvantDos: 0, turnovers: 0, rdv: 0 };
for (const seed of seeds) {
  const st = makeMatch({ full: true, seed }), cfg = matchCfg({ shotRange: 20, chrono: { periodes: 2, duree: DUR, pause: 10 }, ...over }); o.n++;
  let seen = 0, lastRestart = null; const pend = []; let carry = null, carry2 = null;
  for (let i = 0; i < DUR * 60 * 2.4; i++) {
    matchStep(st, 1 / 60, cfg); if (st.restart?.type === 'fin') break;
    const R = st.restart;
    if (R && R.type !== 'engagement' && R !== lastRestart?.r && st.t >= (R.at ?? 0) - 0.5) { lastRestart = { r: R }; const team = R.team; const near = st.players.filter((q) => q.team === team && !q.keeper && q.down <= 0 && hyp(q.p[0] - st.ball.p[0], q.p[2] - st.ball.p[2]) <= 6).length; const K = (o.restarts[R.type] ??= { n: 0, s: 0, gros: 0 }); K.n++; K.s += near; if (near >= 5) K.gros++; }
    for (const w of pend) { if (w.done) continue; const q = st.players[w.to]; const dy = Math.abs(wrap(q.yaw - w.yaw0)); if (dy > w.maxTurn) w.maxTurn = dy; if (!w.recu && st.ball.owner === w.to) { w.recu = true; o.recues++; w.turnAvant = w.maxTurn; w.yawR = q.yaw; const q2 = st.players[w.to]; const dx = q2.p[0] - w.p0[0], dz = q2.p[2] - w.p0[1]; const sv = Math.hypot(w.v0[0], w.v0[1]); if (sv > 1.5 && Math.hypot(dx, dz) > 1.5 && (dx * w.v0[0] + dz * w.v0[1]) / (sv * Math.hypot(dx, dz)) < -0.3) o.retour++; const aFrom = Math.atan2(st.ball.v[2], st.ball.v[0]) + Math.PI; if (sv > 1.5 && Math.abs(wrap(aFrom - q2.yaw)) > 1.92) o.dosRecu++; } if (st.t - w.t > 3) { w.done = true; if (w.maxTurn > 2.1) o.demi++; if (w.recu) { if (w.turnAvant > 2.1) { o.demiAvant++; const mv = Math.hypot(w.v0[0], w.v0[1]) > 1.5; if (mv) o.demiAvantCourse++; else o.demiAvantArret++; if (w.dos0) o.demiAvantDos++; } else if (w.maxTurn > 2.1) o.demiApres++; } } }
    for (; seen < st.events.length; seen++) { const e = st.events[seen];
      if (e.type === 'turnover') o.turnovers++; if (e.type === 'pass' && e.rdv != null) o.rdv++; if (e.type === 'pass' && e.to != null && e.to >= 0 && st.players[e.to] && st.players[e.by]) { const r = st.players[e.to], p = st.players[e.by]; o.passes++; const aBall = Math.atan2(p.p[2] - r.p[2], p.p[0] - r.p[0]); const dos0 = Math.abs(wrap(aBall - r.yaw)) > 1.92; if (dos0) o.dos++; pend.push({ dos0, t: st.t, to: e.to, yaw0: r.yaw, maxTurn: 0, done: false, p0: [r.p[0], r.p[2]], v0: [r.v[0], r.v[1]] }); } }
    { const L = st.ball.ledger?.releases; const last = L && L.length ? L[L.length - 1] : null; const ow0 = st.ball.owner;
      if (ow0 == null && last && last.cause === 'conduite' && (!carry2 || carry2.by !== last.by || carry2.n !== L.length)) carry2 = { by: last.by, n: L.length, max: 0, t0: st.t, v0: hyp(st.ball.v[0], st.ball.v[2]), d05: null, vp0: hyp(st.players[last.by].v[0], st.players[last.by].v[1]), tMax: 0, vbMax: 0, vpMax: 0, touches: 0, ev0: st.events.length };
      if (carry2 && ow0 == null) { const pp = st.players[carry2.by]; const d = hyp(pp.p[0] - st.ball.p[0], pp.p[2] - st.ball.p[2]); if (d > carry2.max) { carry2.max = d; carry2.tMax = st.t - carry2.t0; carry2.vbMax = hyp(st.ball.v[0], st.ball.v[2]); carry2.vpMax = hyp(pp.v[0], pp.v[1]); } if (carry2.d05 == null && st.t - carry2.t0 >= 0.5) carry2.d05 = d; }
      if (carry2 && ow0 != null) { o.pousse.push(carry2.max); if (carry2.max > 2.5) o.pousseLoin++; o.v0.push(carry2.v0); if (carry2.d05 != null) o.d05.push(carry2.d05); if (ow0 !== carry2.by) o.perdu++; else { o.repris.push(carry2.max); o.tRepris.push(st.t - carry2.t0); } if (carry2.max > 2.5 && ow0 === carry2.by && o.log.length < 12) o.log.push(`max ${carry2.max.toFixed(1)} m à +${carry2.tMax.toFixed(1)} s (v0 ballon ${carry2.v0.toFixed(1)}, porteur ${carry2.vp0.toFixed(1)} → ballon ${carry2.vbMax.toFixed(1)} / porteur ${carry2.vpMax.toFixed(1)} au max ; ${ow0 === carry2.by ? 'repris' : 'PERDU → ' + ow0} ; événements : ${st.events.slice(carry2.ev0).map((e) => e.type + (e.by != null ? ':' + e.by : '')).slice(0, 6).join(' ')})`); carry2 = null; } }
    const ow = st.ball.owner, q = ow != null ? st.players[ow] : null;
    if (st.phase === 'carry' && q && !q.keeper) { const d = hyp(q.p[0] - st.ball.p[0], q.p[2] - st.ball.p[2]), v = hyp(q.v[0], q.v[1]);
      if (v > 2) { o.dist.push(d); if (!carry || carry.id !== ow) carry = { id: ow, max: 0 }; if (d > carry.max) carry.max = d; } }
    else if (carry) { o.touches.push(carry.max); if (carry.max > 2.5) o.loin++; carry = null; }
  }
}
const q = (a, x) => { a = [...a].sort((u, v) => u - v); return a.length ? a[Math.floor(x * a.length)] : NaN; }, pct = (a, b) => (100 * a / Math.max(1, b)).toFixed(1);
console.log(`${o.n} × ${(DUR / 60).toFixed(0)} min ${JSON.stringify(over).slice(0, 80)}`);
console.log(`(1) remises — corps de l'équipe qui remet à ≤ 6 m du ballon juste avant la remise : ${Object.entries(o.restarts).map(([k, v]) => `${k} ${(v.s / v.n).toFixed(1)} (${v.n} ; ≥ 5 corps : ${pct(v.gros, v.n)} %)`).join(' ; ')}`);
console.log(`(2) passes ${o.passes} (reçues ${o.recues}) : ballon venant de derrière le regard du receveur au départ ${pct(o.dos, o.passes)} % ; demi-tour du receveur (> 120° en 1,5 s) ${pct(o.demi, o.passes)} % ; RECEVEUR LANCÉ QUI REVIENT SUR SES PAS pour recevoir (v > 1,5 m/s, déplacement > 1,5 m à contre-course) ${pct(o.retour, o.recues)} % des reçues ; BALLON REÇU DANS LE DOS d'un receveur en course (le ballon arrive à > 110° de son regard, v > 1,5) ${pct(o.dosRecu, o.recues)} % des reçues ; demi-tour AVANT la réception (le receveur se retourne vers le ballon) ${pct(o.demiAvant, o.recues)} % des reçues, APRÈS seulement ${pct(o.demiApres, o.recues)} % — parmi les demi-tours AVANT : receveur en course (v > 1,5) ${o.demiAvantCourse}, à l'arrêt ${o.demiAvantArret}, ballon parti dans son dos ${o.demiAvantDos}`);
console.log(`    garde-fou : passes ${(o.passes / o.n).toFixed(0)} / match, pertes (turnover) ${(o.turnovers / o.n).toFixed(0)} / match, passes au rendez-vous ${o.rdv} (${pct(o.rdv, o.passes)} %)`);
for (const l of o.log) console.log('   poussée', l);
console.log(`(3 bis) POUSSÉES de conduite (release 'conduite' → reprise) : distance max ballon-porteur p50 ${q(o.pousse, 0.5).toFixed(2)} m, p90 ${q(o.pousse, 0.9).toFixed(2)}, p99 ${q(o.pousse, 0.99).toFixed(2)} ; poussées à > 2,5 m ${pct(o.pousseLoin, o.pousse.length)} % (${o.pousse.length}) ; vitesse du ballon au lâcher p50 ${q(o.v0, 0.5).toFixed(1)} p90 ${q(o.v0, 0.9).toFixed(1)} m/s ; distance à + 0,5 s p50 ${q(o.d05, 0.5).toFixed(2)} p90 ${q(o.d05, 0.9).toFixed(2)} ; poussées perdues (reprises par un autre) ${pct(o.perdu, o.pousse.length)} % ; POUSSÉES REPRISES PAR LE PORTEUR : max p50 ${q(o.repris, 0.5).toFixed(2)} p90 ${q(o.repris, 0.9).toFixed(2)} p99 ${q(o.repris, 0.99).toFixed(2)} m, temps de reprise p50 ${q(o.tRepris, 0.5).toFixed(2)} p90 ${q(o.tRepris, 0.9).toFixed(2)} s`);
console.log(`(3) conduite (porteur > 2 m/s) : distance ballon-porteur p50 ${q(o.dist, 0.5).toFixed(2)} m, p90 ${q(o.dist, 0.9).toFixed(2)}, p99 ${q(o.dist, 0.99).toFixed(2)} ; max par port p50 ${q(o.touches, 0.5).toFixed(2)} p90 ${q(o.touches, 0.9).toFixed(2)} ; ports où le ballon part à > 2,5 m ${pct(o.loin, o.touches.length)} % (${o.touches.length} ports)`);
