// sonde MC03 (Modèle 03, ballon) — 2 distance d'arrêt, 3 BRD à 3,2 m/s, 4 crise de traînée (v à 20 m), 5 portance C_L aux trois points et déviation de coup franc, 14 knuckle.
import { kick, simulate, magnusCoefficient, dragCoefficient, BALL } from '../../assets/starter/src/engine/ball.js';
const dist = (p) => Math.hypot(p[0], p[2]);
const stopD = (v0) => { const s = kick([0, BALL.radius, 0], { speed: v0, elevation: 0 }); const { path } = simulate(s, { dt: 1 / 120, maxT: 30, until: (st) => Math.hypot(st.v[0], st.v[2]) < 0.05 }); const last = path[path.length - 1]; return { d: dist(last.p), t: last.t }; };
console.log(`2   distance d'arrêt au sol (gazon standard) : ${[4, 8, 12, 16, 20, 25].map((v) => `${v} m/s → ${stopD(v).d.toFixed(1)} m`).join(' ; ')} (book gazon sec : 20 m/s → 47,2 m, 25 m/s → ~70 m ; 30 m en 2,33 s à 20)`);
console.log(`3   BRD (lâcher à 3,20 m/s) : ${stopD(3.2).d.toFixed(1)} m (norme UEFA 4-8 m)`);
const vAt20 = (v0) => { const s = kick([0, 0.5, 0], { speed: v0, elevation: 0.05 }); const { path } = simulate(s, { dt: 1 / 120, maxT: 5, until: (st) => dist(st.p) >= 20 || st.p[1] < 0.05 }); const last = path[path.length - 1]; const p = last.p, v = last.v; return dist(p) >= 19.5 ? Math.hypot(v[0], v[1], v[2]) : NaN; };
console.log(`4   vitesse à 20 m selon v0 : ${[10, 14, 18, 22, 26, 30, 35].map((v) => `${v} → ${vAt20(v).toFixed(1)}`).join(' ; ')} m/s (cible : inflexion vers 16-20, saturation 17-21) ; Cd(8) ${dragCoefficient(8).toFixed(2)}, Cd(13) ${dragCoefficient(13).toFixed(2)}, Cd(25) ${dragCoefficient(25).toFixed(2)} (book 0,474 sous-critique, 0,17-0,21 super)`);
const clAt = (Sp) => { const v = 25, w = Sp * v / BALL.radius; return magnusCoefficient(v, w); };
console.log(`5a  C_L(Sp) : Sp 0,06 → ${clAt(0.06).toFixed(3)} (cible 0,14 ±0,02), 0,19 → ${clAt(0.19).toFixed(3)} (0,29 ±0,02), 0,31 → ${clAt(0.31).toFixed(3)} (0,33 ±0,03)`);
const devs = []; for (const v0 of [25, 27.5, 30]) for (const rev of [5, 7, 9]) { const s = kick([0, 0.3, 0], { speed: v0, elevation: 0.18, spinAxis: [0, 1, 0], spinRev: rev }); const { path } = simulate(s, { dt: 1 / 120, maxT: 4, until: (st) => st.p[0] >= 25 }); const last = path[path.length - 1]; devs.push(Math.abs(last.p[2])); }
devs.sort((a, b) => a - b); console.log(`5b  déviation latérale à 25 m d'un coup franc (25-30 m/s, 5-9 tr/s) : p50 ${devs[Math.floor(devs.length / 2)].toFixed(2)} m, min ${devs[0].toFixed(2)}, max ${devs[devs.length - 1].toFixed(2)} (cible 4,5-6,0 loi de puissance ; 3,5-4,5 droite)`);
const s0 = kick([0, 0.3, 0], { speed: 20, elevation: 0.08, spinRev: 0 }); const { path: path0 } = simulate(s0, { dt: 1 / 120, maxT: 3, until: (st) => st.p[0] >= 25 }); const zs = path0.map((q) => q.p[2]); console.log(`14  frappe sans effet à 20 m/s : excursion latérale max ${Math.max(...zs.map(Math.abs)).toFixed(3)} m (knuckle réel : ≤ 0,45 m, λ 12-15 m — 0 = pas de knuckleball)`);
