// sonde 264 — les flux RNG nommés : (1) LA NEUTRALITÉ (test 8 du Modèle 01, forme forte) : un tirage AJOUTÉ sur le générateur séquentiel (un st.rnd() par image dans cfg.avantMouvement) laisse le match BIT-IDENTIQUE sous la clé (hash des positions et des événements) et le déplace sans elle ; (2) le monde sous la clé est un autre tirage de la même distribution (2 × 45 min : passes, tirs, buts).
import { makeMatch, matchStep, matchCfg } from '/home/user/three-js-aaa-agent-skill/skills/threejs-aaa/assets/starter/src/engine/match-sim.js';
const mode = process.argv[2] ?? 'hash', over = JSON.parse(process.argv[3] ?? '{}');
const hash = (seed, dur, o, dummy) => { const st = makeMatch({ full: true, seed }), cfg = matchCfg({ shotRange: 20, ...o, ...(dummy ? { avantMouvement: (s, c) => { matchCfg({}).avantMouvement?.(s, c); s.rnd(); } } : {}) }); /* le crochet du 255 porte déjà piegeApply : on l'enchaîne, on ne le remplace pas */ let h = 2166136261 >>> 0; const mix = (x) => { h ^= Math.round(x * 100) & 0xffff; h = Math.imul(h, 16777619) >>> 0; };
  for (let i = 0; i < dur * 60; i++) { matchStep(st, 1 / 60, cfg); if (i % 6 === 0) { for (const p of st.players) { mix(p.p[0]); mix(p.p[2]); } mix(st.ball.p[0]); mix(st.ball.p[2]); } }
  mix(st.events.length); mix(st.score?.[0] ?? 0); mix(st.score?.[1] ?? 0); return h.toString(16).padStart(8, '0') + ' (' + st.events.length + ' évts, ' + (st.score ?? []).join('-') + ')'; };
if (mode === 'hash') { for (const seed of [3, 7]) { const a = hash(seed, 300, over, false), b = hash(seed, 300, over, true); console.log(`graine ${seed} ${JSON.stringify(over)} : sans tirage ajouté ${a} ; avec ${b} → ${a === b ? 'IDENTIQUE' : 'DÉPLACÉ'}`); } }
else { let passes = 0, tirs = 0, buts = 0, n = 0; for (const seed of [3, 7]) { const st = makeMatch({ full: true, seed }), cfg = matchCfg({ shotRange: 20, chrono: { periodes: 2, duree: 2700, pause: 10 }, ...over }); n++; for (let i = 0; i < 2700 * 60 + 600; i++) { matchStep(st, 1 / 60, cfg); if (st.restart?.type === 'fin') break; } passes += st.events.filter((e) => e.type === 'pass').length; tirs += st.events.filter((e) => e.type === 'shot').length; buts += (st.score?.[0] ?? 0) + (st.score?.[1] ?? 0); }
  console.log(`${n} × 45 min ${JSON.stringify(over)} — passes ${(passes / n).toFixed(0)} / match, tirs ${(tirs / n).toFixed(1)}, buts ${(buts / n).toFixed(1)}`); }
